version: '2.8'
services:
  admin:
    build: 
      context: .
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    depends_on:
      - admin_db
    environment:
      - DB_HOST=admin_db             
      - DB_DATABASE=admin     
      - DB_USERNAME=root      
      - DB_PASSWORD=root 


  admin_db:
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: admin
    volumes:
      - ./storage/dbdata:/var/lib/mysql
    ports:
      - "33060:3306"

  phpmyadmin:
    image: phpmyadmin:latest
    depends_on:
      - admin_db
    environment:
      PMA_HOST: admin_db
      MYSQL_ROOT_PASSWORD: root
    ports:
      - "8080:80"