version: '3.9'

services:
  admin:
    container_name: admin
    build: 
      context: .
      dockerfile: Dockerfile
    volumes:
      - .:/app 
    ports:
      - "8000:8000"
    depends_on:
      - admin_db
    environment:
      - DB_HOST=admin_db             
      - DB_DATABASE=admin     
      - DB_USERNAME=root      
      - DB_PASSWORD=root

    deploy:
      resources:
        limits:
          memory: 512M 
          cpus: "0.5"  

  admin_phpmyadmin:
    container_name: admin_phpmyadmin
    image: phpmyadmin:latest
    depends_on:
      - admin_db
    environment:
      PMA_HOST: admin_db
      MYSQL_ROOT_PASSWORD: root
    ports:
      - "8080:80"
    deploy:
      resources:
        limits:
          memory: 256M
          cpus: "0.25"

  admin_db:
    container_name: admin_db
    image: mysql:8.0
    command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: admin
    volumes:
      - ./storage/dbdata:/var/lib/mysql
    ports:
      - "3308:3306"
    deploy:
      resources:
        limits:
          memory: 1G  
          cpus: "1.0" 
